services:
  postgres_db:
    image: pgvector/pgvector:0.6.2-pg16
    container_name: postgres_db
    volumes:
      - postgres_dbs_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    restart: always
    ports:
      - "5432:5432"
    expose:
      - "5432"
    healthcheck:
      test: "exit 0"
    networks:
      - my-network

  pg_admin:
    image: dpage/pgadmin4
    container_name: pgadmine
    restart: always
    ports:
      - "80:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres_db
    networks:
      - my-network

volumes:
  postgres_dbs_data:
  pgadmin_data:

networks:
  my-network:
    external: true